### ISSUE TITLE
Cannot use plugin on IE-11

### ISSUE THREAD

**Issue by WuglyakBolgoink** [fundsaccess/ng-chiptan#8]
Hallo guys!

we can not use this plugin on `IE-11`
![image](https://user-images.githubusercontent.com/2271337/86160758-8692f100-bb0c-11ea-9219-6dbd6634b071.png)

Because `dist` folder contain JS-file in `ES6` format. Please convert this into `ES5` or do it additionally.
![image](https://user-images.githubusercontent.com/2271337/86160844-ae825480-bb0c-11ea-9742-e79f3307f161.png)

**Comment by fundsaccess** [comment]
Hello @WuglyakBolgoink,

this library was just updated to v1. Now babel-loader is used to transpile es6 to es5. 

I just tested the showcase on IE11, it works. Please update the library to solve you problem. 

Best,

fundsaccess F/E team

**Comment by WuglyakBolgoink** [comment]
fixed
